---
title: "Iteration and List Columns"
author: "Soomin You"
date: "2024-10-29"
output: github_document
---

Settings 

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load key packages. 

```{r}
library(tidyverse)
library(rvest)
```


## Here's some lists 

```{r}
l = list(
  vec_numeric = 1:4, 
  unif_sample = runif(100), 
  mat = matrix(1:8, nrow = 2, ncol = 4, byrow = TRUE), 
  summary = summary(rnorm(1000))
)

l

l$mat

l[["mat"]][1,3]

l[[1]]
l[[4]]
```


Make a list that's hopefully a bit more useful. 


```{r}
list_norm = 
  list(
    a = rnorm(20, 0, 5), 
    b = rnorm(20, 4, 5), 
    c = rnorm(20, 0, 10), 
    d = rnorm(20, 4, 10)
  )

list_norm[["b"]]
```


Let's reuse teh function we wrote the last time. 


```{r}
mean_and_sd = function(x) {
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  out_df = 
    tibble(
      mean = mean_x,
      sd = sd_x 
    )
  
  return(out_df)
  
}
```


Let's use teh function to take mean and sd of all samples. 

```{r}
mean_and_sd(list_norm[["a"]])
mean_and_sd(list_norm[["b"]])
mean_and_sd(list_norm[["c"]])
mean_and_sd(list_norm[["d"]])
```

## Use a for loop

Create a output list, and run a for loop 

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norm[[i]])
  
}

output
```







