---
title: "writing_functions"
author: "Soomin You"
date: "2024-10-24"
output: github_document
---

Settings 

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load key packages. 

```{r}
library(readxl)
library(rvest)
```

## Writing my first function!!

as an example, here's a z-score computation 

```{r}
x_vec = rnorm(n = 25, mean = 10, sd = 3.5)

(x_vec - mean(x_vec)) / sd(x_vec)
```

Now i';; write a function to do this. 

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)){
    stop("x needs to be numeric")
  }
  
  if (length(x) < 5) {
    stop("you need at least five numbers to compute the z score")
  }

  z = (x - mean(x)) / sd(x) 
  
  return(z)
  
}

z_scores(x = x_vec)
```

Does this always work? 

```{r, error = TRUE}
z_scores(x = 3)
z_scores(x = c("my", "name", "is", "jeff"))
```


## A new function! 

```{r}
mean_and_sd = function(x) {
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  out_df = 
    tibble(
      mean = mean_x,
      sd = sd_x 
    )
  
  return(out_df)
  
}

mean_and_sd(x_vec)
```

## Check stuff using a simulation 

```{r}
sim_df = 
  tibble(
    x = rnorm(30, 10, 5)
  )

sim_df |>
  summarize(
    mean = mean(x), 
    sd = sd(x)
  )
```

Simulation function to check sample mean and sd.

```{r}
sim_mean_sd = function(samp_size, true_mean, true_sd){
  
  sim_df = 
    tibble(
      x = rnorm(samp_size, true_mean, true_sd)
  )
  
  out_df = 
    sim_df |>
    summarize(
      mean = mean(x), 
      sd = sd(x)
  )
  
  return(out_df)
  
}

sim_mean_sd(samp_size = 30, true_mean = 4, true_sd = 12)
sim_mean_sd(true_mean = 4, true_sd = 12, samp_size = 30)
sim_mean_sd(3000, 4, 12)

```
 


## Revisit the LoTR words 

```{r}
fellowship_df = 
  read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship") |>
  janitor::clean_names()

two_towers_df = 
  read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers") |>
  janitor::clean_names()

return_king_df = 
  read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king") |>
  janitor::clean_names()
```


Let's do this using a function instead. 

```{r}
lotr_import = function(cell_range, movie_title) {
  
  movie_df = 
    read_excel("./data/LotR_Words.xlsx", range = cell_range) |>
    mutate(movie = movie_title) |>
    janitor::clean_names() |>
    pivot_longer(
      col = female:male, 
      names_to = "sex", 
      values_to = "words"
    ) |>
    select(movie, everything())
  
  return(movie_df)
  
}

lotr_import(cell_range = "B3:D6", movie_title = "fellowship")
lotr_import(cell_range = "F3:H6", movie_title = "two_towers")
lotr_import("J3:L6", "return_king")

lotr_df = 
  bind_rows(
    lotr_import(cell_range = "B3:D6", movie_title = "fellowship"), 
    lotr_import(cell_range = "F3:H6", movie_title = "two_towers"), 
    lotr_import("J3:L6", "return_king")
  )
```


## NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

marj_table = 
  nsduh_html |>
  html_table() |>
  nth(1) |>
  slice(-1) |>
  mutate(drug = "marj")

cocaine_table = 
  nsduh_html |>
  html_table() |>
  nth(4) |>
  slice(-1) |>
  mutate(drug = "cocaine")

heroin_table = 
  nsduh_html |>
  html_table() |>
  nth(5) |>
  slice(-1) |>
  mutate(drug = "heroin")

```


Make this into a function 

```{r}
nsduh_table_format = function(html, table_num, table_name){
  
  out_table = 
    html |>
    html_table() |>
    nth(table_num) |>
    slice(-1) |>
    mutate(drug = table_name) |>
    select(-contains("P Value"))
  
  return(out_table)
  
}

bind_rows(
  nsduh_table_format(html = nsduh_html, 1, "marj"), 
  nsduh_table_format(html = nsduh_html, 4, "cocaine"), 
  nsduh_table_format(html = nsduh_html, 5, "heroin")
)
```


## DO THIS INSTEAD: 

```{r}
source("source/nsduh_table_format.R")

bind_rows(
  nsduh_table_format(html = nsduh_html, 1, "marj"), 
  nsduh_table_format(html = nsduh_html, 4, "cocaine"), 
  nsduh_table_format(html = nsduh_html, 5, "heroin")
)

```


